### PR TITLE
Optimized step matching and updated code to support Kotlin 1.0.4.

### PR DESCRIPTION
**Pull request by RodrigoQuesadaDev**
Hi, I just updated the plugin to work with latest Kotlin version.

### CODE REVIEW

**Comment by harley84** [comment]
Hi Rodrigo,
Apologies for not giving enough attention to this project. I'm currently out of country and will review and merge your changes when I get back in about 2 weeks.

Thanks for your contribution

**Comment by RodrigoQuesadaDev** [comment]
Alright no problem, thanks for replying back.

**Comment by harley84** [comment]
Hi Rodrigo
I finally have time to look at this now and I'm also having problems to compile and run the plugin fully in the sandbox. Can you please explain how did you prepare the workspace? 
I mean, I see in IntellijBehave.iml file a reference to kotlin-plugin library. I would be very grateful if you explain where was it taken from and how did you import it to the project

Thanks in advance

**Comment by RodrigoQuesadaDev** [comment]
Hi harley84, you can get the corresponding plugin from here: https://plugins.jetbrains.com/plugin/6954 (1.0.4-release-IJ2016.1-112, you need to click previous updates button). Just unzip the file and copy Kotlin/lib/kotlin-plugin.jar to providedLib (and update library dependencies on IntelliJ accordingly).

**Comment by harley84** [comment]
Hi Rodrigo
Looks like I'm not going to have time to invest in this project anytime soon. Would you like to become a collaborator?

**Comment by RodrigoQuesadaDev** [comment]
Sure, no problem, although I probably won't be investing time on this project anytime soon either, so don't expect too many contributions from me. :)

**Comment by harley84** [comment]
@witspirit , Can you please add Rodrigo as collaborator in Github?
Rodrigo, what is your email so I can add you as a collaborator in plugins.jetbrains.com?

**Comment by RodrigoQuesadaDev** [comment]
Okay, here it is: rodrigoquesada@gmail.com

**Comment by harley84** [comment]
@RodrigoQuesadaDev , do you have a jetbrains account? Turns out I can't invite you by email... What is your username there?

**Comment by RodrigoQuesadaDev** [comment]
Yes, I do have a Jetbrains account. My username there is _rodrigodev_

**Comment by harley84** [comment]
I've added you there

**Comment by RodrigoQuesadaDev** [comment]
Cool, I'll try to get some time to update the code/plugin later then, thanks!

**Comment by RodrigoQuesadaDev** [comment]
Hi @harley84 , I just got some time to work on this plugin and updated its build system to use Gradle (with the [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin)), so it's now easier to build the plugin and run the tests. I'll update the README file a bit just to reflect those new changes if that's okay with you.

Also, I think it would probably be a good idea to bump the plugin version to 1.6 some time after these commits (I think there is at least some minor NPE fix by another user that I could probably check into) and release it to jetbrains plugins repo. I can do the release-to-jetbrains part because you added me as a colllaborator there, though I can't make any changes to this repo yet (I think I was never added as a collaborator here :) ).

**Pull request merged**
